# Generated by Django 4.1 on 2022-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80)),
                ('dokon_nomi', models.CharField(max_length=50)),
                ('telefon_raqami', models.IntegerField()),
                ('manzil', models.CharField(max_length=80)),
            ],
        ),
    ]
