# Generated by Django 4.1 on 2022-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=80)),
                ('client', models.CharField(max_length=80)),
                ('sana', models.DateField()),
                ('miqdor', models.IntegerField()),
                ('umumiy_summa', models.IntegerField()),
                ('tolandi', models.IntegerField()),
                ('nasiya', models.IntegerField()),
            ],
        ),
    ]
